sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PQgS6wuN87SYXbrS70lBqUio1WvwsgLq3/dNPc+xlIRu+YB3YITvb0Vuz9LPWbEZvzwc0RBXNg54Xg5GQA3S1AWyqSay+E9oMHufhjB3II4wpYc+l9vrcAMK3p5VFvPD9AD6H1L+ysmjWKW70+qj/9HTK5x3/zzdoXvkr4s3xfsQyoTzBt9/QlOxhaTJA+QV0OOnLRtBEhEaDgCz3ZLvnEVaqmu66ai56Z3MzkOD//6PCWUtIfOmYoUTXb2lwB4jMj38dcGwDAcj+qorQiS9UuiZFW+7b0S4Tj0aURHfMZbTwLtlsNLk5fxeyu0Rm220RsWwdl2YpwTqn7M37yxBNutTQdMuX3WHqOEy/Sr4ycr+qon2QBjkvLb4xp50LFBrgU0Vp2spn5gAIST7QKG930Q5uB4QeIDOEOuAqCc8P5Ho9rEaBY7TTB0sg8E9IfNpToArO0VaitOAiCyo5/OkQmQic3wwDKUvNBf4SrJnETJHmVQraSfXT07NZhxar21l/DMRGgLOuf9ms32nOSuiGjhaCfBL1blG78s6sE6cDC7LNsvUIK/W+k3UBePR2UhC0SuKWkRPwObFtdA2/G9/OicUuIRlu92BDFBWQhi/R9JnOgLOE5yAI7QrT9i/9mGelH10vPHswPsbyTFwr9QSYoNktZWlfRUZ4TGlAZTyOr8=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/The-Life-of-the-Bee_4511
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy